import Head from "next/head";
import Banner from "../components/banner/banner.component";
import Card from "../components/card/card.component";
import styles from "../styles/home.module.css";
import coffeeStores from "../data/coffee-stores.json";

export default function Home({ coffeeStores }) {
  console.log(coffeeStores);
  const { container, main, cardLayout } = styles;

  function handleOnClick() {
    console.log("clicked");
  }

  return (
    <div className={container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={main}>
        <Banner
          buttonText="View stores nearby"
          onClickHandler={handleOnClick}
        />
        <div className={cardLayout}>
          {coffeeStores.map((coffeeStore) => (
            <Card key={coffeeStore.id} coffeeStore={coffeeStore} />
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      coffeeStores,
    },
  };
}
